"""
CodeNebula - Git History Analyzer
Extracts commit history, change statistics, and contributor information
"""

import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List

try:
    import git
    HAS_GITPYTHON = True
except ImportError:
    HAS_GITPYTHON = False


class GitAnalyzer:
    """Analyze Git repository history"""
    
    AI_COMMENT_PATTERNS = [
        r'generated by ai',
        r'created by copilot',
        r'auto-generated',
        r'linted by',
        r'formatted by',
        r'// TODO:',
        r'# TODO:',
        r'AI:',
        r'Bot:',
    ]
    
    # Mark as AI active zone if single commit changes > 200 lines and has AI comments
    AI_CHANGE_THRESHOLD = 200
    
    def __init__(self):
        self.enabled = HAS_GITPYTHON
    
    def analyze(self, repo_path: Path) -> Dict:
        """Analyze Git repository"""
        if not self.enabled:
            return self._empty_result("GitPython not installed")
        
        try:
            repo = git.Repo(repo_path)
        except git.InvalidGitRepositoryError:
            return self._empty_result("Not a valid Git repository")
        
        if repo.bare:
            return self._empty_result("Cannot analyze bare repository")
        
        commits = []
        contributors = {}
        file_changes = {}
        ai_active_zones = []
        
        try:
            for commit in repo.iter_commits(max_count=500):  # Limit to 500
                commit_info = self._extract_commit_info(commit)
                commits.append(commit_info)
                
                # Count contributors
                author = commit.author.name
                contributors[author] = contributors.get(author, 0) + 1
                
                # Count file changes
                if commit.stats:
                    for file_path, stats in commit.stats.files.items():
                        if file_path not in file_changes:
                            file_changes[file_path] = {'additions': 0, 'deletions': 0, 'commits': 0}
                        file_changes[file_path]['additions'] += stats.get('insertions', 0)
                        file_changes[file_path]['deletions'] += stats.get('deletions', 0)
                        file_changes[file_path]['commits'] += 1
                
                # Detect AI active zones
                if self._is_ai_commit(commit):
                    ai_active_zones.append({
                        'commit': commit.hexsha[:8],
                        'author': author,
                        'date': commit.committed_datetime.isoformat(),
                        'message': commit.message[:100]
                    })
        
        except Exception as e:
            return self._empty_result(f"Analysis error: {str(e)}")
        
        return {
            'commits': commits,
            'contributors': contributors,
            'file_changes': file_changes,
            'ai_active_zones': ai_active_zones,
            'metadata': {
                'total_commits': len(commits),
                'total_contributors': len(contributors),
                'ai_commit_ratio': len(ai_active_zones) / max(len(commits), 1),
                'analysis_time': datetime.now().isoformat()
            }
        }
    
    def _extract_commit_info(self, commit) -> Dict:
        """Extract single commit information"""
        return {
            'sha': commit.hexsha[:8],
            'full_sha': commit.hexsha,
            'author': commit.author.name,
            'email': commit.author.email,
            'date': commit.committed_datetime.isoformat(),
            'message': commit.message.strip(),
            'short_message': commit.message.split('\n')[0][:80],
            'stats': {
                'files_changed': commit.stats.total.get('files', 0),
                'insertions': commit.stats.total.get('insertions', 0),
                'deletions': commit.stats.total.get('deletions', 0)
            }
        }
    
    def _is_ai_commit(self, commit) -> bool:
        """Detect if commit was generated by AI"""
        message = commit.message.lower()
        
        # Check for AI-related comments
        has_ai_marker = any(re.search(pattern, message) for pattern in self.AI_COMMENT_PATTERNS)
        
        # Check change size
        total_changes = commit.stats.total.get('insertions', 0) + commit.stats.total.get('deletions', 0)
        is_large_change = total_changes > self.AI_CHANGE_THRESHOLD
        
        return has_ai_marker or is_large_change
    
    def _empty_result(self, reason: str) -> Dict:
        """Return empty result"""
        return {
            'commits': [],
            'contributors': {},
            'file_changes': {},
            'ai_active_zones': [],
            'metadata': {
                'error': reason,
                'total_commits': 0
            }
        }
